import { Fighter } from './fighter';

export const FIGHTERS: Fighter[] = [
  { id: '01', name: 'Mario' },
  { id: '02', name: 'Donkey Kong' },
  { id: '03', name: 'Link' },
  { id: '04', name: 'Samus / Dark Samus' },
  { id: '05', name: 'Yoshi' },
  { id: '06', name: 'Kirby' },
  { id: '07', name: 'Fox' },
  { id: '08', name: 'Pikachu' },
  { id: '09', name: 'Luigi' },
  { id: '10', name: 'Ness' },
  { id: '11', name: 'Captain Falcon' },
  { id: '12', name: 'Jigglypuff' },
  { id: '13', name: 'Peach / Daisy' },
  { id: '14', name: 'Bowser' },
  { id: '15', name: 'Ice Climbers' },
  { id: '16', name: 'Sheik' },
  { id: '17', name: 'Zelda' },
  { id: '18', name: 'Dr. Mario' },
  { id: '19', name: 'Pichu' },
  { id: '20', name: 'Falco' },
  { id: '21', name: 'Marth' },
  { id: '21e', name: 'Lucina' },
  { id: '22', name: 'Young Link' },
  { id: '23', name: 'Ganondorf' },
  { id: '24', name: 'Mewtwo' },
  { id: '25', name: 'Roy / Chrom' },
  { id: '26', name: 'Mr. Game & Watch' },
  { id: '27', name: 'Meta Knight' },
  { id: '28', name: 'Pit / Dark Pit' },
  { id: '29', name: 'Zero Suit Samus' },
  { id: '30', name: 'Wario' },
  { id: '31', name: 'Snake' },
  { id: '32', name: 'Ike' },
  { id: '33', name: 'Squirtle' },
  { id: '34', name: 'Ivysaur' },
  { id: '35', name: 'Charizard' },
  { id: '36', name: 'Diddy Kong' },
  { id: '37', name: 'Lucas' },
  { id: '38', name: 'Sonic' },
  { id: '39', name: 'King Dedede' },
  { id: '40', name: 'Olimar' },
  { id: '41', name: 'Lucario' },
  { id: '42', name: 'R.O.B.' },
  { id: '43', name: 'Toon Link' },
  { id: '44', name: 'Wolf' },
  { id: '45', name: 'Villager' },
  { id: '46', name: 'Mega Man' },
  { id: '47', name: 'Wii Fit Trainer' },
  { id: '48', name: 'Rosalina & Luma' },
  { id: '49', name: 'Little Mac' },
  { id: '50', name: 'Greninja' },
  { id: '51', name: 'Mii Brawler' },
  { id: '52', name: 'Mii Swordfighter' },
  { id: '53', name: 'Mii Gunner' },
  { id: '54', name: 'Palutena' },
  { id: '55', name: 'PAC-MAN' },
  { id: '56', name: 'Robin' },
  { id: '57', name: 'Shulk' },
  { id: '58', name: 'Bowser Jr' },
  { id: '59', name: 'Duck Hunt' },
  { id: '60', name: 'Ryu' },
  { id: '60e', name: 'Ken' },
  { id: '61', name: 'Cloud' },
  { id: '62', name: 'Corrin' },
  { id: '63', name: 'Bayonetta' },
  { id: '64', name: 'Inkling' },
  { id: '65', name: 'Ridley' },
  { id: '66', name: 'Simon / Richter' },
  { id: '67', name: 'King K Rool' },
  { id: '68', name: 'Isabelle' },
  { id: '69', name: 'Incineroar' },
  { id: '70', name: 'Piranha Plant' }
];